// ────────────────────────────────────────────────────────────
// ERRENDIS — Articles de blog v4
// Maillage interne ajouté sur tous les articles
// Type p-link : paragraphe avec liens [[texte|/url]]
// ────────────────────────────────────────────────────────────

export const posts = [

  // ══════════════════════════════════════════════════════════
  // BLOC 1 — ARTICLES ORIGINAUX
  // ══════════════════════════════════════════════════════════

  {
    slug: 'signes-remplacer-excel-logiciel-metier',
    title: '7 signes qu\u2019il est temps de remplacer votre tableur Excel par un logiciel métier',
    excerpt: 'Excel est un excellent outil de calcul, mais un mauvais système de gestion. Voici les signaux qui ne trompent pas — et comment passer à autre chose sans chaos.',
    date: '2026-06-15',
    category: 'Gestion d\u2019entreprise',
    readingTime: '12 min',
    seoTitle: '7 signes qu\u2019il faut remplacer Excel par un logiciel métier — Guide 2026',
    seoDescription: 'Fichiers dupliqués, erreurs de saisie, aucune traçabilité : 7 signaux concrets qui indiquent qu\u2019il est temps de passer à un logiciel de gestion métier spécialisé au Maroc.',
    content: [
      { type: 'p', text: 'Excel a longtemps été le premier réflexe de toute entreprise qui démarre : gratuit (ou presque), familier, flexible. Le problème n\u2019est pas Excel en lui-même — c\u2019est excellent pour du calcul ponctuel — mais son usage comme système de gestion d\u2019une activité entière : patients, stock, commandes, dossiers clients. Dans cet article, nous allons voir sept signaux concrets qui indiquent qu\u2019il est temps de passer à autre chose, et comment structurer cette transition sans perturber votre activité.' },
      { type: 'h2', text: '1. Plusieurs versions du même fichier circulent' },
      { type: 'p', text: '« Planning_final_v3_DEF.xlsx » envoyé par email à toute l\u2019équipe : si cette situation vous est familière, c\u2019est le symptôme le plus courant. Sans base de données centralisée, chaque copie devient une source de vérité concurrente. Ce problème s\u2019aggrave avec la taille de l\u2019équipe — à deux personnes, on s\u2019en sort. À dix, c\u2019est ingérable.' },
      { type: 'h2', text: '2. La saisie prend plus de temps que le travail lui-même' },
      { type: 'p-link', text: 'Ressaisir une même information dans trois fichiers différents est un signal clair qu\u2019un système unique ferait gagner du temps. Dans un [[laboratoire d\u2019analyses médicales|/produits/labya]], par exemple, saisir manuellement les résultats d\u2019automates représente 45 minutes par jour de travail purement administratif sans valeur ajoutée médicale.' },
      { type: 'h2', text: '3. Aucune traçabilité de qui a modifié quoi' },
      { type: 'p-link', text: 'Dans un secteur réglementé — santé, [[distribution médicale|/produits/medira]], transport — savoir qui a modifié une donnée n\u2019est pas un confort mais souvent une obligation légale. Dans le cadre d\u2019un audit ISO 15189 pour un laboratoire ou d\u2019un contrôle ONSSA pour un distributeur médical, l\u2019absence de traçabilité peut entraîner des sanctions.' },
      { type: 'h2', text: '4. Les formules cassent à chaque modification' },
      { type: 'p', text: 'Un fichier Excel devenu trop complexe finit toujours par se fissurer : une ligne insérée casse une formule, une colonne supprimée décale tout un calcul. Ces fichiers dépendent souvent d\u2019une seule personne qui "sait comment il marche". Quand cette personne quitte l\u2019entreprise, le système s\u2019effondre.' },
      { type: 'h2', text: '5. Vous ne pouvez pas répondre en temps réel à une question simple' },
      { type: 'p-link', text: '« Combien de dossiers sont en cours aujourd\u2019hui ? » devrait avoir une réponse immédiate. Dans un [[centre d\u2019hémodialyse|/produits/dialya]] qui doit réorganiser le planning en urgence, ou une [[agence de location|/produits/rentara]] qui doit savoir combien de véhicules sont disponibles ce soir, l\u2019information doit être accessible en secondes.' },
      { type: 'h2', text: '6. La collaboration est impossible au-delà de 3 personnes' },
      { type: 'p', text: 'Excel était conçu pour un utilisateur à la fois. Dans une entreprise avec un commercial, un magasinier et un comptable qui travaillent simultanément, un logiciel métier avec des rôles distincts remplace avantageusement trois fichiers qui ne se synchronisent pas.' },
      { type: 'h2', text: '7. Votre croissance est limitée par votre outil' },
      { type: 'p', text: 'C\u2019est le signal le plus sérieux. Quand vous refusez des commandes parce que vous ne pouvez pas gérer le volume, ou quand vous passez plus de temps à gérer vos fichiers qu\u2019à développer votre activité — votre outil est devenu un frein à votre croissance.' },
      { type: 'h2', text: 'Comment réussir la transition sans chaos' },
      { type: 'p-link', text: 'Commencez par identifier le module le plus critique, migrez-le en conservant Excel en parallèle pendant 4 à 6 semaines, puis étendez progressivement. Pour aller plus loin, consultez notre guide sur la [[digitalisation d\u2019un centre d\u2019hémodialyse|/blog/digitaliser-centre-hemodialyse-maroc]] ou notre article sur la [[gestion de stock FEFO pour le médical|/blog/fefo-fifo-gestion-stock-medical]].' },
      { type: 'p-link', text: 'Chez Errendis, nous construisons des [[logiciels de gestion SaaS spécialisés par métier|/produits/]] — [[Labya|/produits/labya]] pour les laboratoires, [[Dialya|/produits/dialya]] pour la dialyse, [[Medira|/produits/medira]] pour la distribution médicale, [[Logistara|/produits/logistara]] pour le transit — avec un accompagnement à la migration inclus.' },
    ],
    relatedProducts: ['dialya', 'medira', 'logistara'],
  },

  {
    slug: 'fefo-fifo-gestion-stock-medical',
    title: 'FEFO vs FIFO : quelle méthode pour la gestion de stock médical au Maroc ?',
    excerpt: 'Deux méthodes de rotation de stock qui ne répondent pas au même besoin. Pour le médical marocain, le choix ne se discute pas — et les conséquences d\u2019une mauvaise gestion sont lourdes.',
    date: '2026-06-22',
    category: 'Distribution médicale',
    readingTime: '11 min',
    seoTitle: 'FEFO vs FIFO gestion stock médical Maroc — Guide complet 2026',
    seoDescription: 'FEFO et FIFO : comprendre la différence, pourquoi le médical marocain doit privilégier le FEFO, et comment un logiciel automatise cette règle pour éviter les périmés.',
    content: [
      { type: 'p-link', text: 'Dans la [[distribution d\u2019équipements médicaux au Maroc|/produits/medira]], la gestion de stock ne se résume pas à savoir combien d\u2019unités sont disponibles — elle doit aussi savoir lesquelles sortir en premier. Une mauvaise rotation des stocks peut avoir des conséquences financières (pertes sur produits périmés), réglementaires (sanctions ONSSA) et surtout sanitaires.' },
      { type: 'h2', text: 'FIFO : premier entré, premier sorti' },
      { type: 'p', text: 'Le FIFO fait sortir en priorité les produits arrivés en premier en stock. C\u2019est la méthode la plus intuitive, adaptée à une grande partie des secteurs — mais elle suppose une corrélation entre la date d\u2019arrivée en stock et l\u2019urgence de sortie. Cette corrélation n\u2019existe pas toujours dans le médical.' },
      { type: 'h2', text: 'FEFO : premier périmé, premier sorti' },
      { type: 'p', text: 'Le FEFO fait sortir en priorité les produits dont la date de péremption est la plus proche, indépendamment de leur date d\u2019arrivée. C\u2019est la méthode recommandée par l\u2019OMS et imposée dans la plupart des référentiels qualité internationaux pour le médical.' },
      { type: 'h2', text: 'Les risques concrets au Maroc' },
      { type: 'p-link', text: 'Un distributeur médical qui vend des produits périmés s\u2019expose à un retrait d\u2019agrément et des poursuites. Dans un [[laboratoire d\u2019analyses médicales|/produits/labya]], un réactif périmé peut donner des résultats faussement normaux — avec des impacts directs sur le diagnostic patient. Voir aussi notre article sur la [[conformité ISO 15189 pour les laboratoires marocains|/blog/conformite-iso-15189-laboratoire-maroc]].' },
      { type: 'h2', text: 'Appliquer le FEFO manuellement : pourquoi c\u2019est impossible à grande échelle' },
      { type: 'p', text: 'Avec quelques dizaines de références, un magasinier rigoureux peut appliquer le FEFO manuellement. Avec plusieurs centaines de références — situation courante dans la distribution médicale — c\u2019est humainement impossible sans système automatisé.' },
      { type: 'h2', text: 'Comment un logiciel automatise le FEFO' },
      { type: 'p', text: 'Un logiciel conforme au FEFO doit enregistrer la date de péremption de chaque lot à la réception, proposer automatiquement le bon lot à sortir, alerter à J-90 et J-30 avant péremption, et bloquer la sortie d\u2019un lot périmé avec traçabilité complète.' },
      { type: 'h2', text: 'FEFO et traçabilité : deux faces de la même médaille' },
      { type: 'p-link', text: 'En cas de rappel produit, un distributeur doit identifier en quelques heures tous les clients ayant reçu un lot concerné. Sans traçabilité numérique, cet exercice peut prendre plusieurs jours. Pour les [[appels d\u2019offres de dispositifs médicaux|/blog/appel-offres-dispositifs-medicaux-maroc]], cette traçabilité est souvent une exigence contractuelle. [[Medira|/produits/medira]], le logiciel Errendis pour distributeurs médicaux, intègre nativement FEFO et traçabilité des lots.' },
    ],
    relatedProducts: ['medira', 'dialya'],
  },

  {
    slug: 'digitaliser-centre-hemodialyse-maroc',
    title: 'Digitaliser un centre d\u2019hémodialyse au Maroc : guide complet et bonnes pratiques',
    excerpt: 'Dossier patient, planning des séances, biologie intégrée et facturation AMO : comment structurer la digitalisation d\u2019un centre de dialyse marocain sans perturber les soins.',
    date: '2026-06-29',
    category: 'Santé',
    readingTime: '13 min',
    seoTitle: 'Digitaliser centre hémodialyse Maroc — Guide complet 2026',
    seoDescription: 'Dossier patient dialysé, planning postes/générateurs, biologie HL7, facturation AMO/CNOPS/CNSS : guide étape par étape pour digitaliser un centre d\u2019hémodialyse au Maroc.',
    content: [
      { type: 'p-link', text: 'La gestion d\u2019un centre d\u2019hémodialyse au Maroc combine des exigences cliniques strictes et une charge administrative lourde. Pour comprendre le contexte épidémiologique, consultez notre article sur l\u2019[[insuffisance rénale chronique au Maroc|/blog/insuffisance-renale-chronique-maroc-enjeux-gestion]]. La majorité des centres gèrent encore leur activité avec des registres papier et des fichiers Excel — une situation qui génère des risques cliniques et des pertes financières évitables.' },
      { type: 'h2', text: 'Étape 1 : commencer par le dossier patient' },
      { type: 'p', text: 'Le dossier patient (antécédents, accès vasculaire, historique de séances) est la fondation sur laquelle tout le reste s\u2019appuie. Un dossier numérique bien structuré permet à n\u2019importe quel membre de l\u2019équipe soignante de retrouver en quelques secondes l\u2019information dont il a besoin — même en l\u2019absence du médecin référent.' },
      { type: 'h2', text: 'Étape 2 : le planning des séances' },
      { type: 'p', text: 'Organiser postes, générateurs et créneaux à la main devient ingérable au-delà d\u2019une dizaine de patients. Un planning visuel numérique avec réaffectation par glisser-déposer transforme cette gestion quotidienne.' },
      { type: 'h2', text: 'Étape 3 : l\u2019intégration biologie' },
      { type: 'p-link', text: 'Une intégration avec le [[laboratoire d\u2019analyses partenaire|/produits/labya]] via HL7 permet de faire remonter automatiquement les résultats dans le dossier patient, avec des alertes sur les valeurs critiques. L\u2019objectif n\u2019est pas de remplacer le jugement médical, mais d\u2019éliminer le risque qu\u2019une valeur critique passe inaperçue.' },
      { type: 'h2', text: 'Étape 4 : la facturation AMO, CNOPS, CNSS' },
      { type: 'p', text: 'Un logiciel qui génère automatiquement les bordereaux à partir des séances réalisées, avec suivi des rejets et correction assistée, peut réduire de 20 à 30% le délai de recouvrement.' },
      { type: 'h2', text: 'Les erreurs à éviter' },
      { type: 'p-link', text: 'Erreur 1 : digitaliser sans former l\u2019équipe. Erreur 2 : abandonner les dossiers papier du jour au lendemain. Erreur 3 : ne pas tester la facturation sur un mois complet avant de couper l\u2019ancien système. Pour les professionnels qui gèrent aussi la partie analyses, notre article sur [[Excel vs logiciel métier|/blog/signes-remplacer-excel-logiciel-metier]] couvre ces étapes de transition en détail. [[Dialya|/produits/dialya]], le logiciel Errendis pour centres d\u2019hémodialyse, est conçu autour de ces réalités marocaines.' },
    ],
    relatedProducts: ['dialya'],
  },

  // ══════════════════════════════════════════════════════════
  // BLOC 2 — ARTICLES PRIORITÉ 2
  // ══════════════════════════════════════════════════════════

  {
    slug: 'logiciel-gestion-laboratoire-analyses-medicales-maroc-2026',
    title: 'Logiciel de gestion pour laboratoire d\u2019analyses médicales au Maroc : guide complet 2026',
    excerpt: 'Réception, automates, validation biologique, ISO 15189, facturation AMO : tout ce que doit couvrir un logiciel pour laboratoire de biologie médicale au Maroc en 2026.',
    date: '2026-07-07',
    category: 'Santé',
    readingTime: '13 min',
    seoTitle: 'Logiciel gestion laboratoire analyses médicales Maroc 2026 — Guide complet',
    seoDescription: 'Connexion automates, ISO 15189/GBEA, facturation AMO/CNOPS/CNSS, portail médecin : guide complet pour choisir un logiciel de gestion laboratoire d\u2019analyses médicales au Maroc.',
    content: [
      { type: 'p', text: 'Le Maroc compte aujourd\u2019hui plus de 1 200 laboratoires d\u2019analyses médicales privés. Ce secteur est en forte croissance, porté par le déploiement de l\u2019AMO et l\u2019augmentation de la demande en biologie de routine et spécialisée. Pourtant, une majorité gèrent encore leur activité avec des registres papier et des fichiers Excel.' },
      { type: 'h2', text: 'Module réception : la première impression compte' },
      { type: 'p', text: 'La réception est le premier contact du patient avec le laboratoire. Un logiciel performant doit permettre de créer le dossier en moins de 2 minutes, par scan de l\u2019ordonnance ou de la CIN, avec détection automatique des analyses prescrites et identification de l\u2019organisme payeur.' },
      { type: 'h2', text: 'Connexion aux automates : zéro ressaisie' },
      { type: 'p', text: 'La connexion bidirectionnelle avec les automates (Cobas, Sysmex, Architect, VIDAS) supprime la ressaisie manuelle des résultats — principale source d\u2019erreurs de transcription. Des études estiment ces erreurs entre 0,1% et 0,5% des résultats, ce qui représente plusieurs dizaines d\u2019erreurs par mois dans un laboratoire à fort volume.' },
      { type: 'h2', text: 'ISO 15189 et GBEA : la conformité intégrée' },
      { type: 'p-link', text: 'La norme ISO 15189 et le GBEA imposent une documentation extensive. Pour comprendre comment un logiciel couvre chaque exigence de cette norme, consultez notre guide dédié : [[ISO 15189 au Maroc — comment décrocher l\u2019accréditation|/blog/conformite-iso-15189-laboratoire-maroc]].' },
      { type: 'h2', text: 'Facturation multi-organisme' },
      { type: 'p', text: 'Un laboratoire conventionné doit gérer des règles de facturation différentes pour chaque organisme (CNOPS, CNSS, AMO Tadamon, mutuelles privées). Un logiciel qui automatise ces règles peut représenter un gain de 3 à 5 heures par semaine pour le personnel administratif.' },
      { type: 'h2', text: 'Portail médecin prescripteur' },
      { type: 'p-link', text: 'Un portail web sécurisé pour les médecins prescripteurs est aujourd\u2019hui un avantage concurrentiel fort. Plusieurs laboratoires marocains rapportent une augmentation de leur volume de prescriptions de 10 à 20% après sa mise en place. Si votre laboratoire travaille avec un centre de dialyse, notre article sur la [[digitalisation d\u2019un centre d\u2019hémodialyse|/blog/digitaliser-centre-hemodialyse-maroc]] explique comment connecter les deux systèmes. [[Labya|/produits/labya]], le logiciel Errendis, intègre l\u2019ensemble de ces fonctions.' },
    ],
    relatedProducts: ['labya'],
  },

  {
    slug: 'logiciel-location-voiture-maroc-comparatif',
    title: 'Logiciel de gestion pour agence de location de voiture au Maroc : guide 2026',
    excerpt: 'Planning flotte, contrats dématérialisés, suivi GPS, entretien et alertes : ce que doit faire un logiciel pour agence de location de voitures au Maroc.',
    date: '2026-07-08',
    category: 'Location automobile',
    readingTime: '12 min',
    seoTitle: 'Logiciel location voiture Maroc 2026 — Guide complet et fonctionnalités',
    seoDescription: 'Planning flotte temps réel, contrats et EDL dématérialisés, GPS, entretien, multi-agences : guide complet pour choisir un logiciel de gestion agence de location voiture au Maroc.',
    content: [
      { type: 'p', text: 'Le secteur de la location de voitures au Maroc est l\u2019un des plus dynamiques de l\u2019économie du tourisme et de la mobilité d\u2019affaires. Avec plus de 13 millions de touristes accueillis en 2024, les agences font face à une pression croissante sur leur capacité à gérer des flottes plus grandes. Pourtant, beaucoup d\u2019agences indépendantes gèrent encore leur flotte sur des tableurs.' },
      { type: 'h2', text: 'Le planning flotte : la fonction la plus critique' },
      { type: 'p', text: 'La disponibilité en temps réel de chaque véhicule est la fonction la plus critique. Un planning mal tenu génère des doubles réservations catastrophiques pour l\u2019image de l\u2019agence, des véhicules indisponibles non anticipés et une sous-utilisation de la flotte.' },
      { type: 'h2', text: 'Contrats et états des lieux dématérialisés' },
      { type: 'p', text: 'Un état des lieux sur tablette avec photos horodatées et signature électronique du client élimine quasiment tous les litiges à la restitution. C\u2019est la fonction qui a le plus d\u2019impact sur la satisfaction client et la rentabilité de l\u2019agence.' },
      { type: 'h2', text: 'Entretien préventif et alertes kilométriques' },
      { type: 'p', text: 'Le logiciel doit suivre le kilométrage de chaque véhicule, déclencher des alertes avant les échéances de vidange et de contrôle technique, et garder l\u2019historique complet d\u2019entretien pour chaque véhicule — utile aussi pour la revente.' },
      { type: 'h2', text: 'Gestion multi-agences' },
      { type: 'p-link', text: 'Les enseignes qui opèrent sur plusieurs villes (Casablanca, Rabat, Marrakech, Agadir, Tanger) ont besoin d\u2019une vue unifiée sur l\u2019ensemble de la flotte. Pour aller plus loin sur l\u2019optimisation des outils métiers, consultez notre article [[7 signes qu\u2019il est temps de remplacer Excel|/blog/signes-remplacer-excel-logiciel-metier]]. [[Rentara|/produits/rentara]], le logiciel Errendis pour agences de location, est conçu pour ces configurations multi-sites.' },
    ],
    relatedProducts: ['rentara'],
  },

  {
    slug: 'logiciel-gestion-restaurant-maroc-guide-2026',
    title: 'Logiciel de gestion restaurant au Maroc : guide complet 2026',
    excerpt: 'Caisse, plan de salle, menu QR, écran cuisine KDS, fiches techniques et stocks : le guide complet pour choisir un logiciel de gestion restaurant au Maroc.',
    date: '2026-07-09',
    category: 'Restauration',
    readingTime: '12 min',
    seoTitle: 'Logiciel gestion restaurant Maroc 2026 — Guide complet fonctionnalités',
    seoDescription: 'Caisse, plan de salle, menu digital QR, KDS, fiches techniques, stocks et fidélité : guide complet pour choisir un logiciel de gestion restaurant au Maroc en 2026.',
    content: [
      { type: 'p', text: 'La restauration marocaine est en pleine transformation. L\u2019émergence de chaînes locales structurées et les attentes croissantes d\u2019une clientèle habituée aux standards internationaux créent une pression forte sur les restaurateurs pour professionnaliser leurs opérations.' },
      { type: 'h2', text: 'La caisse : bien plus qu\u2019un tiroir-caisse numérique' },
      { type: 'p', text: 'Une caisse restaurant moderne doit gérer simultanément plusieurs tables ouvertes, accepter plusieurs modes de paiement, gérer les offerts avec traçabilité, et produire un rapport de caisse complet en fin de service en 5 minutes.' },
      { type: 'h2', text: 'L\u2019écran cuisine KDS : éliminer les bons papier' },
      { type: 'p', text: 'Le KDS affiche les commandes par ordre chronologique avec un code couleur selon le temps écoulé. Le chef valide chaque plat prêt d\u2019un toucher — ce qui notifie automatiquement le serveur. Résultat : moins d\u2019erreurs et une traçabilité complète de chaque plat.' },
      { type: 'h2', text: 'Fiches techniques et coût matières' },
      { type: 'p', text: 'Beaucoup de restaurateurs marocains connaissent leur chiffre d\u2019affaires mais ignorent leur coût matières réel par plat. Une fiche technique calcule automatiquement la marge brute de chaque plat et identifie ceux qui érodent la rentabilité.' },
      { type: 'h2', text: 'Gestion des stocks et approvisionnements' },
      { type: 'p-link', text: 'Chaque plat vendu consomme des ingrédients. Un logiciel qui soustrait automatiquement les consommations du stock — avec alertes de seuil — évite les ruptures en service. Pour les établissements qui veulent aller plus loin dans la professionnalisation, notre article [[7 signes pour quitter Excel|/blog/signes-remplacer-excel-logiciel-metier]] couvre les étapes de cette transition. [[Restara|/produits/restara]], le logiciel Errendis, est conçu pour les restaurateurs marocains indépendants et les enseignes.' },
    ],
    relatedProducts: ['restara'],
  },

  {
    slug: 'logiciel-gestion-ecole-privee-maroc-massar',
    title: 'Logiciel de gestion école privée au Maroc : ce que Massar ne fait pas (2026)',
    excerpt: 'Massar gère les établissements publics. Les écoles privées marocaines ont des besoins spécifiques que Massar ne couvre pas. Guide 2026.',
    date: '2026-07-10',
    category: 'Éducation',
    readingTime: '11 min',
    seoTitle: 'Logiciel gestion école privée Maroc 2026 — Ce que Massar ne fait pas',
    seoDescription: 'Paiements scolarité, bulletins, communication parents, cantine, emplois du temps : guide pour choisir un logiciel de gestion école privée ou crèche au Maroc en 2026.',
    content: [
      { type: 'p', text: 'Le secteur de l\u2019enseignement privé marocain regroupe plus de 6 000 établissements, accueillant environ 1,2 million d\u2019élèves. Ces établissements font face à des défis de gestion spécifiques que Massar n\u2019est pas conçue pour adresser.' },
      { type: 'h2', text: 'Ce que Massar ne couvre pas pour les privés' },
      { type: 'p', text: 'Massar ne propose pas : la gestion des frais de scolarité et des paiements, la comptabilité de l\u2019établissement, la cantine et les activités périscolaires, ni la communication directe établissement-parents en dehors du cadre officiel.' },
      { type: 'h2', text: 'La gestion des frais de scolarité' },
      { type: 'p', text: 'Le suivi des frais de scolarité — avec les retards de paiement, les plans d\u2019échéancement et les relances — est une tâche chronophage si faite manuellement. Un logiciel centralise ces données, génère les quittances et produit des rapports d\u2019impayés par classe.' },
      { type: 'h2', text: 'La communication parents : l\u2019application mobile comme standard' },
      { type: 'p', text: 'Les parents veulent recevoir des notifications en temps réel pour les absences, consulter les notes dès leur saisie, voir le menu de cantine et communiquer directement avec les enseignants. Une application mobile parent est aujourd\u2019hui un critère de choix d\u2019établissement.' },
      { type: 'h2', text: 'La cantine et les activités périscolaires' },
      { type: 'p-link', text: 'La gestion de la cantine implique de suivre les présences quotidiennes, facturer selon les formules choisies et gérer les régimes alimentaires particuliers. Pour les crèches et maternelles qui ont des besoins encore plus spécifiques, consultez notre guide [[gestion d\u2019une crèche ou école maternelle au Maroc|/blog/gestion-ecole-maternelle-creche-maroc]]. [[Skolara|/produits/skolara]], le logiciel Errendis, couvre l\u2019ensemble de ces besoins pour les établissements privés marocains.' },
    ],
    relatedProducts: ['skolara'],
  },

  {
    slug: 'logiciel-btp-maroc-suivi-chantier-retenues-garantie',
    title: 'Logiciel BTP au Maroc : suivi chantier, retenues de garantie et CNSS — Guide 2026',
    excerpt: 'Suivi de chantier par phases, retenues de garantie, TVA multi-taux et CNSS intégrés : le guide du logiciel BTP pour entreprises de construction marocaines.',
    date: '2026-07-11',
    category: 'BTP',
    readingTime: '12 min',
    seoTitle: 'Logiciel BTP Maroc 2026 — Suivi chantier, retenues de garantie et CNSS natifs',
    seoDescription: 'Suivi chantier par phases, retenues de garantie, TVA multi-taux, CNSS natifs : guide pour choisir un logiciel de gestion BTP adapté aux entreprises de construction marocaines.',
    content: [
      { type: 'p', text: 'Le BTP représente environ 6% du PIB marocain et emploie plus d\u2019un million de personnes. Pourtant, les PME du BTP restent parmi les moins informatisées de l\u2019économie, gérant leurs chantiers avec des fichiers Excel et leurs déclarations CNSS manuellement.' },
      { type: 'h2', text: 'Les retenues de garantie : une gestion précise indispensable' },
      { type: 'p', text: 'En droit marocain, le maître d\u2019ouvrage peut retenir 5 à 10% de chaque décompte. Ces retenues s\u2019accumulent et sont libérées à la réception provisoire puis définitive. Un logiciel qui calcule automatiquement ce montant sur chaque décompte et alerte à l\u2019approche des dates de libération est indispensable.' },
      { type: 'h2', text: 'La TVA multi-taux dans le BTP marocain' },
      { type: 'p', text: 'La facturation BTP marocaine implique souvent 20%, 14% et 7% sur la même facture selon la nature des travaux et des matériaux. Un logiciel de facturation BTP doit gérer ces multiples taux et produire des factures conformes aux exigences fiscales marocaines.' },
      { type: 'h2', text: 'La CNSS chantier : automatiser les déclarations' },
      { type: 'p', text: 'Le personnel de chantier BTP bénéficie d\u2019un régime CNSS spécifique. L\u2019entreprise doit déclarer mensuellement les heures travaillées par chantier et par employé. Sans logiciel, cette déclaration se fait sur des pointages papier — source majeure d\u2019erreurs.' },
      { type: 'h2', text: 'La gestion des sous-traitants' },
      { type: 'p-link', text: 'Un chantier moyen implique 5 à 10 sous-traitants spécialisés. Le logiciel doit suivre leurs marchés, leurs situations mensuelles et leurs retenues de garantie spécifiques. Pour les entreprises qui veulent comprendre pourquoi Excel ne suffit plus, notre article [[7 signes pour quitter Excel|/blog/signes-remplacer-excel-logiciel-metier]] est un bon point de départ. [[Batira|/produits/batira]], le logiciel Errendis pour entreprises BTP marocaines, intègre nativement toutes ces fonctions.' },
    ],
    relatedProducts: ['batira'],
  },

  {
    slug: 'logiciel-delegues-medicaux-maroc-force-vente-pharma',
    title: 'Logiciel pour délégués médicaux au Maroc : gérer sa force de vente pharma — Guide 2026',
    excerpt: 'CRM médecins, comptes-rendus de visite, gestion des échantillons, objectifs et reporting superviseur : guide pour digitaliser une force de vente pharmaceutique au Maroc.',
    date: '2026-07-12',
    category: 'Pharmacie',
    readingTime: '12 min',
    seoTitle: 'Logiciel délégués médicaux Maroc 2026 — Gérer sa force de vente pharma',
    seoDescription: 'CRM médecins, comptes-rendus visite, échantillons, objectifs et reporting : guide pour digitaliser une force de vente de délégués médicaux au Maroc en 2026.',
    content: [
      { type: 'p', text: 'L\u2019industrie pharmaceutique au Maroc représente un marché de plus de 14 milliards de dirhams. La visite médicale reste le principal canal de promotion des médicaments. Pourtant, la majorité des forces de vente fonctionnent encore avec des rapports Excel et des carnets de visite papier.' },
      { type: 'h2', text: 'Le CRM médecins : la base de données qui fait tout' },
      { type: 'p', text: 'La base médecins doit contenir : coordonnées géolocalisées, spécialité, potentiel de prescription, fréquence de visite cible et historique complet des interactions. Sans cette base centralisée, les délégués travaillent à l\u2019aveugle.' },
      { type: 'h2', text: 'L\u2019optimisation des tournées' },
      { type: 'p-link', text: 'Un délégué non équipé passe 25 à 35% de son temps en déplacements non productifs. Pour un guide complet sur l\u2019optimisation des tournées, consultez notre article dédié : [[optimiser les tournées de délégués médicaux au Maroc|/blog/optimiser-tournees-delegues-medicaux-maroc]].' },
      { type: 'h2', text: 'La gestion des échantillons : conformité et traçabilité' },
      { type: 'p', text: 'La réglementation marocaine encadre strictement la remise d\u2019échantillons. Chaque remise doit être tracée, les stocks alloués contrôlés, et les remises ne peuvent dépasser certains plafonds par médecin.' },
      { type: 'h2', text: 'Le tableau de bord superviseur' },
      { type: 'p-link', text: 'Le responsable régional doit voir en temps réel le taux de couverture, la fréquence moyenne de visite et la performance individuelle des délégués. Pour les laboratoires qui distribuent aussi des équipements médicaux, [[Medira|/produits/medira]] et [[Medikara|/produits/medikara]] peuvent fonctionner ensemble. [[Medikara|/produits/medikara]], le logiciel Errendis, est le seul outil francophone dédié à ce créneau conçu pour le marché marocain.' },
    ],
    relatedProducts: ['medikara'],
  },

  // ══════════════════════════════════════════════════════════
  // BLOC 3 — NOUVEAUX ARTICLES
  // ══════════════════════════════════════════════════════════

  {
    slug: 'conformite-iso-15189-laboratoire-maroc',
    title: 'ISO 15189 au Maroc : comment un logiciel aide votre laboratoire à décrocher l\u2019accréditation',
    excerpt: 'L\u2019accréditation ISO 15189 est le standard de qualité pour les laboratoires médicaux. Comment un logiciel couvre chaque exigence de la norme — guide pratique.',
    date: '2026-07-14',
    category: 'Santé',
    readingTime: '10 min',
    seoTitle: 'ISO 15189 Maroc — Comment un logiciel aide votre laboratoire à l\u2019accréditation',
    seoDescription: 'Accréditation ISO 15189 pour laboratoires marocains : métrologie, CQI, traçabilité, GBEA — comment un logiciel couvre chaque exigence. Guide pratique.',
    content: [
      { type: 'p-link', text: 'L\u2019accréditation ISO 15189 est la reconnaissance internationale de la compétence technique d\u2019un laboratoire de biologie médicale. Pour les laboratoires qui se posent la question d\u2019un logiciel complet, consultez d\u2019abord notre [[guide du logiciel pour laboratoire d\u2019analyses médicales au Maroc|/blog/logiciel-gestion-laboratoire-analyses-medicales-maroc-2026]].' },
      { type: 'h2', text: 'Pourquoi l\u2019ISO 15189 est difficile à obtenir sans logiciel' },
      { type: 'p', text: 'La norme impose une documentation extensive et une traçabilité complète. Gérer cela manuellement représente une charge de travail considérable qui détourne le personnel de son cœur de métier. Un logiciel conçu pour la conformité transforme cette charge en processus automatisés.' },
      { type: 'h2', text: 'La métrologie et le suivi des équipements' },
      { type: 'p', text: 'ISO 15189 exige que tous les équipements soient étalonnés à intervalles définis. Le logiciel doit gérer un registre de tous les équipements avec leurs dates d\u2019étalonnage, des alertes avant les échéances et les certificats associés.' },
      { type: 'h2', text: 'Les contrôles qualité internes (CQI)' },
      { type: 'p', text: 'Les CQI sont des sérums de contrôle passés régulièrement pour vérifier que les automates fonctionnent correctement. Les résultats sont représentés sur des cartes de Levey-Jennings avec les règles de Westgard pour détecter les dérives avant qu\u2019elles n\u2019affectent les résultats patients.' },
      { type: 'h2', text: 'La traçabilité du dossier analytique' },
      { type: 'p-link', text: 'ISO 15189 exige que chaque résultat soit traçable depuis l\u2019ordonnance jusqu\u2019au compte-rendu final. Cette traçabilité est aussi critique dans le contexte de la [[gestion de stock FEFO pour les réactifs|/blog/fefo-fifo-gestion-stock-medical]] — un réactif périmé mal tracé peut compromettre tout un lot de résultats. [[Labya|/produits/labya]], le logiciel Errendis, maintient automatiquement ce fil de traçabilité pour chaque dossier.' },
    ],
    relatedProducts: ['labya'],
  },

  {
    slug: 'insuffisance-renale-chronique-maroc-enjeux-gestion',
    title: 'Insuffisance rénale chronique au Maroc : enjeux et défis de la gestion des centres de dialyse',
    excerpt: 'Le Maroc fait face à une épidémie silencieuse d\u2019insuffisance rénale chronique. Comprendre les enjeux pour mieux gérer un centre de dialyse.',
    date: '2026-07-15',
    category: 'Santé',
    readingTime: '9 min',
    seoTitle: 'Insuffisance rénale chronique Maroc — Enjeux gestion centres de dialyse',
    seoDescription: 'Épidémiologie de l\u2019IRC au Maroc, financement AMO des séances de dialyse, enjeux de gestion des centres : contexte pour les professionnels de la dialyse marocains.',
    content: [
      { type: 'p-link', text: 'L\u2019insuffisance rénale chronique terminale est l\u2019une des pathologies les plus coûteuses à prendre en charge dans le système de santé marocain. Cet article pose le contexte épidémiologique et économique. Pour le guide pratique de digitalisation d\u2019un centre, consultez : [[digitaliser un centre d\u2019hémodialyse au Maroc|/blog/digitaliser-centre-hemodialyse-maroc]].' },
      { type: 'h2', text: 'L\u2019épidémiologie de l\u2019IRC au Maroc' },
      { type: 'p', text: 'Avec une prévalence estimée à 150 cas par million d\u2019habitants et une incidence annuelle d\u2019environ 100 nouveaux cas par million, le Maroc doit prendre en charge près de 35 000 patients dialysés — un chiffre en augmentation constante en raison de la progression du diabète et de l\u2019hypertension artérielle.' },
      { type: 'h2', text: 'Le financement de la dialyse par l\u2019AMO' },
      { type: 'p', text: 'La dialyse est prise en charge à 100% pour les patients couverts (ALD). Cette prise en charge représente la quasi-totalité des revenus d\u2019un centre de dialyse — d\u2019où l\u2019importance critique d\u2019une facturation rigoureuse et d\u2019un suivi serré des remboursements.' },
      { type: 'h2', text: 'Les défis opérationnels des centres marocains' },
      { type: 'p', text: 'Les centres font face à : une demande croissante qui dépasse la capacité installée, des générateurs dont la maintenance est critique, une pénurie de néphrologues et d\u2019infirmiers spécialisés, et des exigences réglementaires croissantes.' },
      { type: 'h2', text: 'Pourquoi la digitalisation est une réponse concrète' },
      { type: 'p-link', text: 'La digitalisation permet d\u2019optimiser l\u2019utilisation des postes, de réduire le temps administratif du personnel soignant, de sécuriser le suivi clinique et de maximiser le recouvrement. Pour les centres qui travaillent en lien avec un laboratoire partenaire, [[Labya|/produits/labya]] et [[Dialya|/produits/dialya]] peuvent être interfacés directement. [[Dialya|/produits/dialya]] a été conçu en réponse à ces défis spécifiques du contexte marocain.' },
    ],
    relatedProducts: ['dialya'],
  },

  {
    slug: 'appel-offres-dispositifs-medicaux-maroc',
    title: 'Appels d\u2019offres dispositifs médicaux au Maroc : comment les gagner et les gérer',
    excerpt: 'Les marchés publics de dispositifs médicaux représentent une part importante du CA des distributeurs marocains. Comment se préparer, répondre et gérer ces contrats efficacement.',
    date: '2026-07-16',
    category: 'Distribution médicale',
    readingTime: '10 min',
    seoTitle: 'Appels d\u2019offres dispositifs médicaux Maroc — Guide pour distributeurs',
    seoDescription: 'Marchés publics de dispositifs médicaux au Maroc : préparation des dossiers, gestion des lots, suivi de livraison et facturation. Guide pratique pour distributeurs médicaux.',
    content: [
      { type: 'p-link', text: 'Les marchés publics de dispositifs médicaux au Maroc représentent un volume d\u2019achats annuel de plusieurs milliards de dirhams. Pour un [[distributeur de dispositifs médicaux|/produits/medira]], décrocher un marché public peut transformer son activité. Pour comprendre les bases de la gestion de stock dans ce secteur, consultez d\u2019abord notre article [[FEFO vs FIFO pour le médical|/blog/fefo-fifo-gestion-stock-medical]].' },
      { type: 'h2', text: 'Comprendre le cadre des marchés publics marocains' },
      { type: 'p', text: 'Les marchés publics sont régis par le décret n°2-12-349. Les achats passent par plusieurs procédures selon les montants : appel d\u2019offres ouvert, appel d\u2019offres restreint, bon de commande. Les consultations sont publiées sur www.marchespublics.gov.ma.' },
      { type: 'h2', text: 'Préparer un dossier solide' },
      { type: 'p', text: 'Un dossier comprend : les documents administratifs (RC, patente, attestation CNSS), les références techniques (fiches produits, certifications CE), les références clients et l\u2019offre financière. Un distributeur qui a toutes ses fiches produits numérisées peut répondre en 48h là où un concurrent mettra une semaine.' },
      { type: 'h2', text: 'Gérer l\u2019exécution du marché' },
      { type: 'p', text: 'Les principales difficultés dans l\u2019exécution : gérer les livraisons partielles selon le calendrier, tracer les numéros de série pour les dispositifs à traçabilité obligatoire, gérer les retenues de garantie et préparer les dossiers de facturation conformes.' },
      { type: 'h2', text: 'Le SAV et le parc installé' },
      { type: 'p-link', text: 'Pour les équipements lourds, le contrat de maintenance est aussi important que la vente. Un logiciel doit suivre le parc installé chez chaque client, planifier les visites préventives et tracer chaque intervention. Si vous gérez aussi des délégués médicaux qui visitent les hôpitaux, [[Medikara|/produits/medikara]] peut compléter [[Medira|/produits/medira]] pour couvrir à la fois la distribution et la promotion terrain.' },
    ],
    relatedProducts: ['medira'],
  },

  {
    slug: 'optimiser-tournees-delegues-medicaux-maroc',
    title: 'Optimiser les tournées de délégués médicaux au Maroc : méthodes et outils',
    excerpt: 'Un délégué médical qui optimise ses tournées peut réaliser 20% de visites supplémentaires sans allonger son temps de travail. Méthodes pratiques et outils pour y arriver.',
    date: '2026-07-17',
    category: 'Pharmacie',
    readingTime: '9 min',
    seoTitle: 'Optimiser tournées délégués médicaux Maroc — Méthodes et outils 2026',
    seoDescription: 'Méthodes pour optimiser les tournées de délégués médicaux au Maroc : segmentation médecins, planification géographique, CRM mobile. Augmentez votre couverture de 20%.',
    content: [
      { type: 'p-link', text: 'La productivité d\u2019un délégué médical se mesure en visites qualitatives par jour. Dans les grandes villes marocaines, les embouteillages créent des contraintes importantes. Cet article est le complément pratique de notre guide sur le [[logiciel pour délégués médicaux au Maroc|/blog/logiciel-delegues-medicaux-maroc-force-vente-pharma]].' },
      { type: 'h2', text: 'La segmentation des médecins cibles' },
      { type: 'p', text: 'Tous les médecins ne méritent pas la même fréquence de visite. La segmentation classe les médecins en catégories A (fort potentiel, visites fréquentes), B (potentiel moyen) et C (faible potentiel). Cette segmentation doit être révisée régulièrement en fonction du comportement de prescription observé.' },
      { type: 'h2', text: 'La construction des tournées : logique géographique vs logique client' },
      { type: 'p', text: 'L\u2019optimale est une combinaison des deux : des secteurs géographiques stables avec une fréquence de visite adaptée à chaque médecin dans le secteur. Un délégué non équipé passe 25 à 35% de son temps en déplacements non productifs.' },
      { type: 'h2', text: 'Les outils numériques d\u2019optimisation' },
      { type: 'p', text: 'Un CRM pour délégués doit proposer une carte géolocalisée de tous les médecins, la visualisation de la fréquence réelle vs cible, une proposition automatique de tournée quotidienne optimisée et la navigation GPS intégrée.' },
      { type: 'h2', text: 'Mesurer l\u2019efficacité' },
      { type: 'p-link', text: 'Les indicateurs clés : taux de couverture, fréquence moyenne, taux de conformité aux cibles, nombre de visites par jour et coût par visite. Ces indicateurs doivent être visibles par le responsable régional en temps réel. Pour les laboratoires qui gèrent aussi la distribution d\u2019équipements, consultez notre article sur les [[appels d\u2019offres dispositifs médicaux|/blog/appel-offres-dispositifs-medicaux-maroc]]. [[Medikara|/produits/medikara]], le logiciel Errendis, intègre ces tableaux de bord en temps réel.' },
    ],
    relatedProducts: ['medikara'],
  },

  {
    slug: 'transit-douane-maroc-guide-operateurs',
    title: 'Transit et dédouanement au Maroc : guide pratique pour les opérateurs logistiques',
    excerpt: 'Régimes douaniers marocains, documents requis, délais et pièges à éviter : le guide pratique du transit et dédouanement au Maroc pour les transitaires.',
    date: '2026-07-18',
    category: 'Logistique',
    readingTime: '11 min',
    seoTitle: 'Transit douane Maroc — Guide pratique opérateurs logistiques 2026',
    seoDescription: 'Régimes douaniers marocains, documents requis pour le dédouanement, délais, pièges et bonnes pratiques : guide pour transitaires et commissionnaires en douane au Maroc.',
    content: [
      { type: 'p-link', text: 'Le Maroc est l\u2019un des pays les mieux positionnés d\u2019Afrique en matière de logistique internationale, avec Tanger Med (premier port d\u2019Afrique) et Casablanca. Pour les transitaires qui veulent comprendre pourquoi la gestion sur Excel atteint ses limites, consultez notre article [[7 signes pour quitter Excel|/blog/signes-remplacer-excel-logiciel-metier]].' },
      { type: 'h2', text: 'Les principaux régimes douaniers marocains' },
      { type: 'p', text: 'La mise à la consommation est le régime le plus courant. L\u2019admission temporaire permet d\u2019importer des équipements pour transformation et réexportation avec suspension des droits. Le transit douanier permet de faire circuler des marchandises sous scellés entre deux bureaux de douane sans paiement des droits.' },
      { type: 'h2', text: 'Les documents requis pour le dédouanement' },
      { type: 'p', text: 'Le dossier comprend typiquement : la facture commerciale (3 exemplaires originaux), la liste de colisage, le connaissement maritime ou la lettre de transport aérien, le certificat d\u2019origine, le certificat de conformité pour les produits réglementés, et l\u2019engagement de change pour les importations de plus de 100 000 DH.' },
      { type: 'h2', text: 'Les délais de dédouanement' },
      { type: 'p', text: 'L\u2019ADII affiche un objectif de 24 à 48h pour les déclarations en circuit vert. Les principales causes de retard : dossiers incomplets, marchandises en circuit rouge (visite physique) et demandes de documents complémentaires.' },
      { type: 'h2', text: 'Gérer un dossier de transit avec un logiciel' },
      { type: 'p-link', text: 'Un dossier de transit implique de suivre simultanément les délais documentaires, de transport, douaniers et de livraison finale. Sans système de suivi, des dossiers peuvent rester bloqués sans que personne ne s\u2019en aperçoive — avec des surestaries à la clé. [[Logistara|/produits/logistara]], le logiciel Errendis pour transitaires marocains, centralise le suivi de tous ces délais avec des alertes automatiques.' },
    ],
    relatedProducts: ['logistara'],
  },

  {
    slug: 'gestion-ecole-maternelle-creche-maroc',
    title: 'Gestion d\u2019une école maternelle ou crèche au Maroc : guide pratique 2026',
    excerpt: 'Inscriptions, présences, repas, paiements et communication parents : comment digitaliser la gestion d\u2019une crèche ou école maternelle au Maroc.',
    date: '2026-07-19',
    category: 'Éducation',
    readingTime: '9 min',
    seoTitle: 'Gestion école maternelle crèche Maroc — Guide pratique digitalisation 2026',
    seoDescription: 'Inscriptions, présences, repas, paiements et communication parents : guide pour digitaliser la gestion d\u2019une crèche ou école maternelle au Maroc avec un logiciel adapté.',
    content: [
      { type: 'p-link', text: 'Les crèches et écoles maternelles privées marocaines font face à des défis de gestion spécifiques. Pour un contexte plus large sur les besoins des établissements privés marocains, consultez notre article [[logiciel de gestion école privée au Maroc|/blog/logiciel-gestion-ecole-privee-maroc-massar]].' },
      { type: 'h2', text: 'Les inscriptions : gérer les listes d\u2019attente' },
      { type: 'p', text: 'Pour les crèches reconnues de Casablanca, Rabat et Marrakech, la demande dépasse souvent l\u2019offre. Un logiciel doit permettre d\u2019ouvrir les inscriptions en ligne, de collecter les dossiers de façon dématérialisée et de gérer les listes d\u2019attente avec attribution automatique des places libérées.' },
      { type: 'h2', text: 'La gestion des présences : une granularité fine' },
      { type: 'p', text: 'À la crèche, les enfants peuvent arriver à des heures différentes et être récupérés par différentes personnes. Le logiciel doit enregistrer les arrivées et départs avec l\u2019identité de la personne qui récupère l\u2019enfant, et gérer les autorisations de récupération définies par les parents.' },
      { type: 'h2', text: 'Le cahier de liaison numérique' },
      { type: 'p', text: 'Les parents veulent savoir comment s\u2019est passée la journée de leur enfant : repas, sieste, activités, éventuels incidents. Un cahier de liaison numérique accessible via l\u2019application parent renforce le lien de confiance avec les familles.' },
      { type: 'h2', text: 'La facturation : flexibilité et rigueur' },
      { type: 'p-link', text: 'La facturation d\u2019une crèche est plus complexe qu\u2019une école classique : tarifs variables selon les formules, repas et activités facturés séparément, déductions possibles pour absences. Un logiciel qui automatise ces calculs représente un gain de temps considérable. [[Skolara|/produits/skolara]], le logiciel Errendis, couvre ces spécificités de la petite enfance marocaine dans ses modules crèche et maternelle.' },
    ],
    relatedProducts: ['skolara'],
  },
  // ────────────────────────────────────────────────────────────
// ERRENDIS — 5 NOUVEAUX ARTICLES (à ajouter dans posts[])
// Copier ces objets dans lib/blog.js avant le ];  final
// ────────────────────────────────────────────────────────────

// ARTICLE 1 — Logistara / Transit
{
    slug: 'tanger-med-opportunites-transitaires-maroc',
    title: 'Tanger Med et le boom logistique marocain : opportunités et défis pour les transitaires',
    excerpt: 'Tanger Med est devenu le premier port d\u2019Afrique. Ce boom logistique crée des opportunités considérables pour les transitaires marocains — à condition d\u2019être équipés pour en profiter.',
    date: '2026-07-20',
    category: 'Logistique',
    readingTime: '9 min',
    seoTitle: 'Tanger Med boom logistique Maroc — Opportunités pour les transitaires 2026',
    seoDescription: 'Tanger Med, premier port d\u2019Afrique : comment les transitaires marocains peuvent profiter du boom logistique avec les bons outils de gestion. Analyse et guide pratique.',
    content: [
      { type: 'p-link', text: 'Tanger Med a traité plus de 9 millions de conteneurs EVP en 2024, consolidant sa position de premier port à conteneurs d\u2019Afrique et de Méditerranée. Ce positionnement stratégique transforme le paysage de la logistique marocaine et crée des opportunités considérables pour les [[transitaires et commissionnaires en douane marocains|/produits/logistara]].' },
      { type: 'h2', text: 'Le contexte : pourquoi Tanger Med change la donne' },
      { type: 'p', text: 'Le développement de Tanger Med n\u2019est pas un phénomène isolé. Il s\u2019inscrit dans une stratégie nationale de positionnement du Maroc comme hub logistique entre l\u2019Europe, l\u2019Afrique subsaharienne et le Moyen-Orient. Le port bénéficie d\u2019un positionnement géographique exceptionnel (14 km de Gibraltar), de zones franches attractives (Tanger Free Zone, Tanger Med Special Agency) et d\u2019infrastructures ferroviaires et autoroutières modernes.' },
      { type: 'h2', text: 'Les opportunités pour les transitaires marocains' },
      { type: 'p', text: 'La croissance du trafic à Tanger Med génère une demande croissante en services de transit et de dédouanement. Les opportunités se concentrent autour de trois axes : la gestion des flux d\u2019importation pour les usines implantées dans les zones franches, le transit de marchandises à destination de l\u2019Afrique subsaharienne via le Maroc, et la consolidation de fret pour les exportateurs marocains qui ciblent les marchés européens.' },
      { type: 'h2', text: 'Les défis : volume, délais et conformité' },
      { type: 'p', text: 'La croissance du volume traité à Tanger Med impose aux transitaires une capacité à gérer de nombreux dossiers simultanément, avec des délais documentaires serrés et des exigences de conformité croissantes de l\u2019ADII. Un transitaire qui gère ses dossiers sur Excel ou WhatsApp ne peut pas absorber une croissance de son activité sans augmenter proportionnellement ses équipes.' },
      { type: 'h2', text: 'La digitalisation : condition nécessaire pour croître' },
      { type: 'p', text: 'Les transitaires qui profiteront du boom logistique marocain seront ceux qui peuvent traiter plus de dossiers avec les mêmes équipes, maintenir une qualité de suivi irréprochable et répondre rapidement aux demandes de leurs clients. Cela implique un système de gestion des dossiers douaniers qui automatise les alertes, centralise les documents et donne une visibilité en temps réel sur chaque expédition.' },
      { type: 'p-link', text: 'Pour aller plus loin sur les procédures douanières marocaines, consultez notre [[guide pratique du transit et dédouanement au Maroc|/blog/transit-douane-maroc-guide-operateurs]]. [[Logistara|/produits/logistara]], le logiciel Errendis pour transitaires marocains, est conçu pour absorber cette croissance sans multiplier les erreurs.' },
    ],
    relatedProducts: ['logistara'],
  },

  // ARTICLE 2 — Batira / BTP
  {
    slug: 'marche-immobilier-maroc-opportunites-promoteurs',
    title: 'Marché immobilier marocain 2026 : enjeux et outils pour les promoteurs et entreprises BTP',
    excerpt: 'Le marché immobilier marocain reste dynamique malgré les tensions sur les coûts de construction. Ce que les promoteurs et entreprises BTP doivent anticiper en 2026.',
    date: '2026-07-21',
    category: 'BTP',
    readingTime: '8 min',
    seoTitle: 'Marché immobilier Maroc 2026 — Enjeux promoteurs et entreprises BTP',
    seoDescription: 'Marché immobilier marocain 2026 : hausse des coûts de construction, pénurie de main-d\u2019œuvre qualifiée, délais de livraison — outils et stratégies pour les promoteurs et entreprises BTP.',
    content: [
      { type: 'p-link', text: 'Le marché immobilier marocain reste l\u2019un des plus actifs d\u2019Afrique du Nord, porté par une demande structurelle en logements et des grands chantiers d\u2019infrastructure publics. Pour les promoteurs immobiliers et les entreprises de construction, 2026 apporte des opportunités mais aussi des tensions qui imposent une gestion plus rigoureuse. Notre [[guide du logiciel BTP au Maroc|/blog/logiciel-btp-maroc-suivi-chantier-retenues-garantie]] couvre les outils disponibles.' },
      { type: 'h2', text: 'La hausse des coûts de construction : gérer les marges sous pression' },
      { type: 'p', text: 'Les coûts des matériaux de construction ont connu des hausses significatives ces dernières années, portées par l\u2019inflation mondiale et les perturbations des chaînes d\u2019approvisionnement. Le ciment, le fer à béton et les matériaux d\u2019isolation ont vu leurs prix augmenter de 15 à 30% sur trois ans. Dans ce contexte, la maîtrise des coûts de chantier n\u2019est plus une option — c\u2019est une condition de survie pour les entreprises BTP à faibles marges.' },
      { type: 'h2', text: 'Les délais de livraison : l\u2019enjeu des pénalités' },
      { type: 'p', text: 'Les marchés de construction marocains incluent systématiquement des pénalités de retard. Dans un contexte de tensions sur les approvisionnements et la main-d\u2019œuvre, respecter les délais devient plus difficile — et plus crucial pour la rentabilité. Un suivi de chantier numérique qui compare en temps réel l\u2019avancement réel au planning prévisionnel permet d\u2019anticiper les dérapages avant qu\u2019ils ne déclenchent des pénalités.' },
      { type: 'h2', text: 'La conformité CNSS : un risque sous-estimé' },
      { type: 'p', text: 'Les contrôles CNSS dans le secteur BTP se sont intensifiés au Maroc. Les entreprises qui ne déclarent pas correctement leurs salariés de chantier s\u2019exposent à des redressements pouvant atteindre plusieurs dizaines de milliers de dirhams. L\u2019automatisation des déclarations CNSS à partir des pointages de chantier est l\u2019un des retours sur investissement les plus rapides d\u2019un logiciel BTP.' },
      { type: 'h2', text: 'La trésorerie : l\u2019enjeu des retenues et des délais de paiement' },
      { type: 'p-link', text: 'Les retenues de garantie et les délais de paiement des maîtres d\u2019ouvrage publics peuvent créer de sérieuses tensions de trésorerie pour les PME du BTP. Un logiciel qui suit automatiquement les retenues cumulées et alerte à l\u2019approche des dates de libération permet d\u2019optimiser le recouvrement. [[Batira|/produits/batira]], le logiciel Errendis pour entreprises BTP marocaines, couvre l\u2019ensemble de ces enjeux.' },
    ],
    relatedProducts: ['batira'],
  },

  // ARTICLE 3 — Medikara / Pharma
  {
    slug: 'industrie-pharmaceutique-maroc-croissance-digitalisation',
    title: 'Industrie pharmaceutique au Maroc : croissance, enjeux et digitalisation de la force de vente',
    excerpt: 'Le marché pharmaceutique marocain croît de 8 à 10% par an. Pour les laboratoires qui veulent gagner des parts de marché, la digitalisation de la force de vente est un avantage concurrentiel décisif.',
    date: '2026-07-22',
    category: 'Pharmacie',
    readingTime: '8 min',
    seoTitle: 'Industrie pharmaceutique Maroc 2026 — Digitalisation force de vente pharma',
    seoDescription: 'Marché pharmaceutique marocain en croissance : comment les laboratoires pharma digitalisent leur force de vente pour gagner des parts de marché. Guide et outils 2026.',
    content: [
      { type: 'p-link', text: 'Le marché pharmaceutique marocain représente plus de 14 milliards de dirhams et croît à un rythme de 8 à 10% par an, porté par le déploiement de l\u2019AMO et l\u2019augmentation de la consommation médicale. Dans ce contexte de croissance, la compétition entre laboratoires pour les parts de prescription s\u2019intensifie. Pour comprendre les outils disponibles, consultez notre [[guide du logiciel pour délégués médicaux au Maroc|/blog/logiciel-delegues-medicaux-maroc-force-vente-pharma]].' },
      { type: 'h2', text: 'Le rôle de la visite médicale dans le marché marocain' },
      { type: 'p', text: 'Contrairement à certains marchés où la prescription est largement influencée par des algorithmes d\u2019aide à la décision ou des plateformes digitales, le marché pharmaceutique marocain reste fortement influencé par la relation directe entre le délégué médical et le médecin prescripteur. La visite médicale est le principal canal promotionnel, ce qui place la performance de la force de vente au cœur de la stratégie commerciale de chaque laboratoire.' },
      { type: 'h2', text: 'L\u2019écart de productivité entre forces de vente digitalisées et non digitalisées' },
      { type: 'p', text: 'Un délégué médical non équipé d\u2019outils numériques réalise en moyenne 6 à 8 visites par jour et passe 30 à 45 minutes par semaine à rédiger ses rapports. Un délégué équipé d\u2019un CRM mobile avec optimisation des tournées peut réaliser 8 à 11 visites par jour et soumettre ses comptes-rendus en temps réel depuis le terrain. Sur une force de vente de 20 délégués, cet écart représente des centaines de visites supplémentaires par mois.' },
      { type: 'h2', text: 'La conformité réglementaire : un enjeu croissant' },
      { type: 'p', text: 'La réglementation marocaine sur la promotion du médicament encadre strictement les pratiques de visite médicale : plafonds de remise d\u2019échantillons, obligations déclaratives, interdictions de certaines pratiques promotionnelles. Les laboratoires qui ne peuvent pas démontrer la conformité de leurs pratiques terrain s\u2019exposent à des sanctions de la Direction du Médicament et de la Pharmacie.' },
      { type: 'p-link', text: 'Pour un guide pratique sur l\u2019optimisation des tournées, consultez notre article [[optimiser les tournées de délégués médicaux au Maroc|/blog/optimiser-tournees-delegues-medicaux-maroc]]. [[Medikara|/produits/medikara]], le logiciel Errendis pour forces de vente pharmaceutiques marocaines, couvre la productivité et la conformité dans un seul outil.' },
    ],
    relatedProducts: ['medikara'],
  },

  // ARTICLE 4 — Skolara / Éducation
  {
    slug: 'enseignement-prive-maroc-croissance-defis-gestion',
    title: 'L\u2019enseignement privé au Maroc : croissance, défis et outils de gestion pour 2026',
    excerpt: 'L\u2019enseignement privé marocain accueille 1,2 million d\u2019élèves et croît chaque année. Comprendre les enjeux de gestion pour rester compétitif dans un secteur en pleine professionnalisation.',
    date: '2026-07-23',
    category: 'Éducation',
    readingTime: '8 min',
    seoTitle: 'Enseignement privé Maroc 2026 — Croissance, défis et outils de gestion',
    seoDescription: 'L\u2019enseignement privé marocain en croissance : comment les écoles privées font face aux défis de gestion administrative, de communication parents et de concurrence entre établissements.',
    content: [
      { type: 'p-link', text: 'L\u2019enseignement privé au Maroc connaît une croissance soutenue depuis une décennie. Plus de 6 000 établissements privés accueillent aujourd\u2019hui 1,2 million d\u2019élèves, soit environ 15% des effectifs scolaires totaux. Cette croissance s\u2019accompagne d\u2019une professionnalisation croissante du secteur et d\u2019attentes parents en hausse. Pour comprendre les outils disponibles, consultez notre [[guide du logiciel pour école privée au Maroc|/blog/logiciel-gestion-ecole-privee-maroc-massar]].' },
      { type: 'h2', text: 'La concurrence entre établissements : la qualité de service comme différenciateur' },
      { type: 'p', text: 'Dans les grandes villes marocaines (Casablanca, Rabat, Marrakech), la concurrence entre écoles privées est intense. Les parents qui peuvent se permettre l\u2019enseignement privé sont exigeants : ils comparent les établissements sur la qualité pédagogique, les résultats aux examens, mais aussi de plus en plus sur la qualité de la communication (notifications en temps réel, bulletins numériques, réactivité de la direction) et la modernité des installations.' },
      { type: 'h2', text: 'La gestion financière : l\u2019enjeu des impayés' },
      { type: 'p', text: 'Le taux d\u2019impayés sur les frais de scolarité est l\u2019un des principaux enjeux financiers des écoles privées marocaines. Sans système de suivi rigoureux, les relances sont tardives et les impayés s\u2019accumulent en fin d\u2019année. Un logiciel de gestion scolaire qui automatise les relances et produit des rapports d\u2019impayés par classe peut réduire significativement ce taux.' },
      { type: 'h2', text: 'Le recrutement des élèves : digitaliser le processus d\u2019inscription' },
      { type: 'p', text: 'La période d\u2019inscription (de mars à juin) est critique pour les établissements privés marocains. Un établissement qui peut ouvrir les inscriptions en ligne, collecter les dossiers de façon dématérialisée et communiquer rapidement avec les familles sur le statut de leur dossier a un avantage concurrentiel significatif sur les établissements qui gèrent encore ce processus manuellement.' },
      { type: 'p-link', text: 'Pour les crèches et maternelles qui ont des besoins spécifiques, consultez notre article [[gestion d\u2019une crèche ou école maternelle au Maroc|/blog/gestion-ecole-maternelle-creche-maroc]]. [[Skolara|/produits/skolara]], le logiciel Errendis pour établissements privés marocains, adresse l\u2019ensemble de ces enjeux.' },
    ],
    relatedProducts: ['skolara'],
  },

  // ARTICLE 5 — Labya / Santé
  {
    slug: 'biologie-medicale-maroc-enjeux-laboratoires-prives',
    title: 'Biologie médicale au Maroc : enjeux et défis des laboratoires privés en 2026',
    excerpt: 'Le secteur de la biologie médicale marocaine est en mutation : déploiement AMO, concentration du marché, exigences qualité croissantes. Comment les laboratoires privés s\u2019adaptent.',
    date: '2026-07-24',
    category: 'Santé',
    readingTime: '8 min',
    seoTitle: 'Biologie médicale Maroc 2026 — Enjeux laboratoires privés analyse médicale',
    seoDescription: 'Biologie médicale marocaine en mutation : impact de l\u2019AMO, concentration du marché, exigences ISO 15189 et digitalisation. Guide pour les laboratoires d\u2019analyses privés au Maroc.',
    content: [
      { type: 'p-link', text: 'Le secteur de la biologie médicale marocaine est en profonde mutation. Le déploiement de l\u2019AMO, la montée des exigences qualité et la concentration progressive du marché transforment les conditions d\u2019exercice des laboratoires privés. Pour comprendre les outils disponibles, consultez notre [[guide du logiciel pour laboratoire d\u2019analyses médicales au Maroc|/blog/logiciel-gestion-laboratoire-analyses-medicales-maroc-2026]].' },
      { type: 'h2', text: 'L\u2019impact du déploiement de l\u2019AMO sur les laboratoires' },
      { type: 'p', text: 'Le déploiement de l\u2019Assurance Maladie Obligatoire (AMO) a deux effets contradictoires sur les laboratoires privés marocains. D\u2019un côté, il augmente le volume d\u2019analyses prescrites en rendant la biologie médicale accessible à une population plus large. De l\u2019autre, il impose une gestion plus complexe de la facturation (multiples organismes, règles différentes, suivi des rejets) et pèse sur les tarifs remboursés.' },
      { type: 'h2', text: 'La concentration du marché : vers des groupes de laboratoires' },
      { type: 'p', text: 'Comme en Europe il y a vingt ans, le marché marocain de la biologie médicale commence à se concentrer. Des groupes rachètent des laboratoires indépendants pour mutualiser les coûts d\u2019automates, les ressources humaines spécialisées et les systèmes d\u2019information. Les laboratoires indépendants qui veulent résister à cette consolidation doivent atteindre une efficacité opérationnelle comparable à celle des grands groupes.' },
      { type: 'h2', text: 'Les exigences qualité : ISO 15189 comme avantage concurrentiel' },
      { type: 'p-link', text: 'L\u2019accréditation ISO 15189 est en train de passer du statut de distinction rare à celui de standard attendu par les prescripteurs et les organismes payeurs exigeants. Notre article sur l\u2019[[accréditation ISO 15189 au Maroc|/blog/conformite-iso-15189-laboratoire-maroc]] détaille comment un logiciel facilite concrètement chaque exigence de la norme. [[Labya|/produits/labya]], le logiciel Errendis pour laboratoires marocains, est conçu pour accompagner cette montée en qualité.' },
    ],
    relatedProducts: ['labya'],
  },

];

export function getPost(slug) {
  return posts.find((p) => p.slug === slug);
}

export function getAllSlugs() {
  return posts.map((p) => p.slug);
}